version: '3'
services:
  development:
    container_name: openfisca_dev_babel
    ports: 
      - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./openfisca_canada_babel:/openfisca/openfisca_canada_babel
